name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 2.0.0-mb.22
homepage: https://github.com/martin-braun/google_maps_place_picker_mb

module:
  androidX: true
environment:
  sdk: ">=2.15.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  google_api_headers: ^4.2.5
  google_maps_flutter: ^2.9.0
  flutter_google_maps_webservices: any
  http: any
  location: ^7.0.1
  provider: ^6.1.2
  tuple: ^2.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


false_secrets:
 - /example/lib/keys.dart
 - /example/android/app/src/main/AndroidManifest.xml
 - /example/ios/Runner/AppDelegate.swift
